### ISSUE TITLE
[BUG] 2.2.0 Infinite Recursion

### ISSUE THREAD

**Issue by nicktrienensfuzz** [kylebrowning/APNSwift#100]
**Describe the bug**
send class it's self to maximum stack size in xcode

**To Reproduce**
included via
        .package(url: "https://github.com/vapor/apns.git", from: "1.0.0")

```
app.get("test") { req -> String in
        try app.apns.send(
            .init(title: "Hello", subtitle: "This is a test from vapor/apns"),
            to: "6a9201adcaa835-------------3"
        ).wait()
        return "Hello, world!"
}
```

This function seems to call it's self forever
```
public func send(rawBytes payload: ByteBuffer,
                     pushType: APNSwiftConnection.PushType = .alert,
                     to deviceToken: String,
                     expiration: Date? = nil,
                     priority: Int? = nil,
                     collapseIdentifier: String? = nil,
                     topic: String? = nil,
                     logger: Logger? = nil,
                     apnsID: UUID? = nil) -> EventLoopFuture<Void> {
        return self.send(
            rawBytes: payload,
            pushType: pushType,
            to: deviceToken,
            expiration: expiration,
            priority: priority,
            collapseIdentifier: collapseIdentifier,
            topic: topic,
            logger: logger ?? self.logger,
            apnsID: apnsID)
    }
```

**Expected behavior**
Hope to see a  sent notification

**Screenshots**
![Screen Shot 2021-01-08 at 11 07 45 AM](https://user-images.githubusercontent.com/15266950/104049709-a2a1da00-51a2-11eb-85a9-550b2a9edad4.png)

**Platform:**
 - OS: mac os x 11.1 (20C69)
 - Version [e.g. 16.04]
Ran from xcode  12.3

**Additional context**

**Comment by kylebrowning** [comment]
can you try with `2.2.1` so we can rule out its not the recent release?

**Comment by kylebrowning** [comment]
Sorry I meant `2.1.0`

**Comment by kylebrowning** [comment]
@mackoj This is related to what we just merged, I've deleted 2.2.0 for now.

**Comment by mackoj** [comment]
Ok thanks I will look into it.

**Comment by mackoj** [comment]
@nicktrienensfuzz with what did you called `send` please ?

**Comment by mackoj** [comment]
Hi, @nicktrienensfuzz  sorry for the inconvenience  but I did't succeed reproducing this bug,  maybe you can help me to reproduce it.

I have cloned https://github.com/vapor/apns.git and change `APNSwiftConfiguration` to something that will work and add my device token and it's working. 

I have cloned https://github.com/kylebrowning/APNSwift and try it's test `APNSwiftExample` and change `APNSwiftConfiguration` to something that will work and add my device token and it's working. I have tried all `send` variation and didn't reproduce this bug.

**Comment by nicktrienensfuzz** [comment]
I used this sample code from the vapor doc site, https://docs.vapor.codes/4.0/apns/
```
try app.apns.send(
            .init(title: "Hello", subtitle: "This is a test from vapor/apns"),
            to: "6a9201adcaa835-------------3"
        )
```

**Comment by nicktrienensfuzz** [comment]
it is working now, using 2.1.0 
Looks like it might have been bad usage on my part too, I was using that in a route so I should have been accessing the `.apns` property on the Request
```
   app.get("test") { req in
        req.apns.send(
            .init(title: "Hello", subtitle: "This is a test from vapor/apns"),
            to: "6a9201adcaa8358e92a01d5e1ba0ccdaad061ccfb7797293da53df807c1c53"
        ).map { "sent" }
    }
```

**Comment by nicktrienensfuzz** [comment]
Thank you so much for your quick response

**Comment by kylebrowning** [comment]
This issue still exists in master.

**Comment by mackoj** [comment]
I'm reproducing it now I'm working on a fix.

**Comment by mackoj** [comment]
@kylebrowning and @nicktrienensfuzz I tried to explain the issue and give a fix here.

https://github.com/vapor/apns/pull/27

**Comment by kylebrowning** [comment]
I think this is resolved.
