### ISSUE TITLE
CNIOBoringSSL build errors on Xcode 12.5 beta 2

### ISSUE THREAD

**Issue by noahemmet** [kylebrowning/APNSwift#102]
**Describe the bug**
Building with Xcode 12.5b2 results in two build errors:
> - 'OPENSSL_ia32cap_get' has different definitions in different modules; definition in module 'CNIOBoringSSL' first difference is function body
> - 'X509V3_CONF_METHOD_st::get_string' from module 'CNIOBoringSSL' is not present in definition of 'struct X509V3_CONF_METHOD_st' in module 'CJWTKitBoringSSL'

Looks like a dependency conflict between swift-nio-ssl and jwt-kit?

**To Reproduce**
1. Download Xcode 12.5 beta 2.
2. Try to build.
3. Note build errors.

**Expected behavior**
No build error.

**Screenshots**
<img width="429" alt="image" src="https://user-images.githubusercontent.com/1952578/108131030-8298ec80-7065-11eb-9837-8e6c8b6f2f93.png">

**Platform:**
 - OS: MacOS 11.2
 - Version: 3.0.0

**Comment by Lukasa** [comment]
Sorry, this was a nasty confluence of JWTKit missing an import guard (vapor/jwt-kit#51) and SwiftNIOSSL not having shipped a 5.4 fix yet. We'll get it fixed shortly.

**Comment by 0xTim** [comment]
Closing in favour of vapor/jwt-kit#51

**Comment by weissi** [comment]
New NIO SSL is also released: https://github.com/apple/swift-nio-ssl/releases/tag/2.10.3

Should now be fixed in both JWT Kit and NIO SSL
