### ISSUE TITLE
No way to handle error?

### ISSUE THREAD

**Issue by dylanreich** [kylebrowning/APNSwift#103]
I see that internally, errors are handled and logged to the console, but in action this causes long-term issues, unless I am missing something. For example, if a user deletes their app, the device token becomes invalid. I see "Response - bad request badDeviceToken" printed out into the console, but I have no way of capturing this. If the 'send' function passed back the  'APNSwiftError.ResponseError' information, I could act on this information and remove the device token from storage. Otherwise, it risks sending extraneous requests to old device tokens and getting blocked from the APNS service.

Is there an easy way of getting this information/something I'm missing? Or a way to update the library? Thank you!

**Comment by kylebrowning** [comment]
Hmm, yeah you could fork the project and submit a PR!

**Comment by VilemKurz** [comment]
@dylanreich I think the error _is_ passed in the result. You can catch the error like this (I am using Vapor wrapper, but that should not make a difference):
```swift
apnsClient.send(
    badgeNotificationData.payload,
    to: badgeNotificationData.deviceToken
)
.flatMapError() {
    if let apnsError = $0 as? APNSwiftError.ResponseError {
        switch apnsError {
        case .badRequest(let responseError):
            switch responseError {
            case .badDeviceToken:
                // Act
            }
        }
    }
}
