### ISSUE TITLE
Bulk send to multiple device tokens

### ISSUE THREAD

**Issue by jaanus** [kylebrowning/APNSwift#107]
**Is your feature request related to a problem? Please describe.**

I am working on an app which sends APNS with the same content to many devices. I was surprised to find out that this library only sends to one device token at a time, which I assume creates many small requests to Apple APNS service. The upstream service supports specifying many device ID-s in a request, and it feels like this library should too.

**Describe the solution you'd like**

I would like to have an API to send APNS which would let me specify many device tokens for one `send` call, as a simple set of Strings.

**Describe alternatives you've considered**

The alternative is to use the current API and send the APNS to several devices one-by-one. This works, it just creates extra network traffic and many small requests instead one bigger request.

**Additional context**

Can’t think of anything, feels quite straightforward.

**Comment by jaanus** [comment]
Upon further reading of the [documentation](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html), I think I’m mistaken. There appears to be no API to bulk-send to multiple tokens. Any bulk-sends that I have seen in other libraries must be handled on the client/sender side.

**Comment by kylebrowning** [comment]
FWIW you can do this with https://github.com/vapor/apns/pull/36
