### ISSUE TITLE
Make it possible to not log

### ISSUE THREAD

**Issue by code28** [kylebrowning/APNSwift#114]
Right now, it's not possible to *not* log, when using e.g. [vapor/apns](https://github.com/vapor/apns) (see also [issue #38](https://github.com/vapor/apns/issues/38)), because the `Request.logger` or `Application.logger` is used as a fallback. When the parameter `logger` is set to `nil`, the logging should be disabled.

As a workaround for now, I'm passing the `SwiftLogNoOpLogHandler` (i.e. `Logger(label: "no op logger", factory: { _ in SwiftLogNoOpLogHandler() })`), but I'd rather pass `nil` to remove logging.

I'm happy to open a PR, but maybe we can discuss first about it: At first it's the `self.logger` fallback for the `APNSwiftClient`, but there is another fallback to `self.configuration.logger` in the `APNSwiftConnection`. The second one is not that a huge deal, because we can just pass `nil` in the configuration. The first one could maybe use some kind of default value instead of `nil` to fallback to `self.logger`. What do you think? Or is this behaviour just like intended?

(A small note, why I want to avoid those logs: They are a bit too verbose for me to be logged in log level `info`. I can achieve almost the same logs from "outside" the library and add some more detail to the logs.)

**Comment by kylebrowning** [comment]
@code28 great question. In order to not have a major version bump we should make the PR such that existing functionality is retained, and new initializers call the "old" ones. 

So basically the default value is the old way, and a new method signature can be adopted by whomever prefers. 

Does that answer your question?

**Comment by kylebrowning** [comment]
Closing in favor of the PR open.
