### ISSUE TITLE
[BUG] TooManyProviderTokenUpdates

### ISSUE THREAD

**Issue by khanlou** [kylebrowning/APNSwift#118]
I am getting a lot (hundreds per day) of TooManyProviderTokenUpdates failures when sending APNS.

My set up is a little strange. I'm not using the Vapor APNS package, but I copied those files into my own project so I could make some tweaks:

1. I have two connection pools, one for sandbox tokens and one for production tokens. (I thought this could be the cause of too many provider updates, but I disabled the sandbox pool entirely, and am still seeing the issue.)
2. When errors like `Unregistered` or `BadDeviceToken` occur in the prod pool, I try them on sandbox, and if that fails I mark the token as "failed".
2. When any other error occur, I record them in the database and post a message to our slack. This is how I found out about the `TooManyProviderTokenUpdates`.

Since I'm not responsible for refreshing the token and that's handled internally by the library, is there anything I can do to stop getting this error? Is there something about my set up that's causing this error to be triggered?

**Comment by kylebrowning** [comment]
I would need to see how exactly youre setting it up, this is not happening in my production servers, or with others I have checked, so it must be the nature of your connection pool.

**Comment by kylebrowning** [comment]
Can we move this to discussion since this is an implementation detail and not a bug.
