### ISSUE TITLE
[BUG]'APNSwiftAlert' is deprecated: renamed to 'APNSwiftAlert'

### ISSUE THREAD

**Issue by wendellli99** [kylebrowning/APNSwift#123]
I receive the following warning message:
'APNSwiftAlert' is deprecated: renamed to 'APNSwiftAlert'
Use 'APNSwiftAlert' instead
with code:
`
let alert = APNSwiftPayload.APNSwiftAlert(
                title: "",
                subtitle:"",
                body: ""
)
`

**Platform:**
 - Xcode 13.1
 - Version apnswift 3.2.0

**Comment by code28** [comment]
It might be a bit confusing, because the name is the same, but there is a difference:
`APNSwiftPayload.APNSwiftAlert` is deprecated.
`APNSwift.APNSwiftAlert` (or just `APNSwiftAlert`) is not.
So I don't see any bug here.
