### ISSUE TITLE
Create iOS app to send push notifications

### ISSUE THREAD

**Issue by Rubenfer** [kylebrowning/APNSwift#25]
In WWDC 2019 Apple introduced the ability to use Swift Packages into iOS apps with Xcode 11.

I've tried to create a sample project with this repository and I got some issues:

- If I try to run on iOS Simulator, it compiles but the app crashes with the error:

> dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib   Referenced from: /Users/.../CoreSimulator/...   Reason: no suitable image found.  Did find:  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib: mach-o, but not built for iOS simulator

- If I try to run on iPhone it doesn't compile with several errors about SSL.

- If I try to run it on Mac using Catalyst (run iPad app on macOS Catalina) I got the message: `

> building for UIKitForMac, but linking in dylib built for macOS, file '/usr/local/Cellar/openssl/1.0.2r/lib/libssl.dylib' for architecture x86_64

Anyone knows a workaround to solve this issues?

**Comment by kylebrowning** [comment]
@Rubenfer I have not tried it yet, but I imagine there's a lot to get right here.

Its possible Xcode doesn't play nicely with iOS Devices libssl and we would need to add another dependency. 

Not sure yet.

**Comment by weissi** [comment]
libssl is not in the iOS/macOS SDKs, you'd need to use the platforms crypto APIs there and not Libre/OpenSSL.

**Comment by kylebrowning** [comment]
Yeah, this is something wed like to fix, but at the current moment, it may be a bit.

**Comment by Rubenfer** [comment]
I think that [Apple CryptoKit](https://developer.apple.com/documentation/cryptokit) would be an alternative to OpenSSL.

Example: https://developer.apple.com/documentation/cryptokit/performing_common_cryptographic_operations

**Comment by kylebrowning** [comment]
@Rubenfer Yeah that would work. Ill probably get to this when my free time frees up :P

Feel free to submit a PR though. It's probably just a lot things like this,

```swift
// Sadly, stat has different signatures with glibc and macOS libc.
#if os(macOS) || os(iOS) || os(watchOS) || os(tvOS) || os(Android)
private let sysStat: @convention(c) (UnsafePointer<CChar>?, UnsafeMutablePointer<stat>?) -> CInt = stat(_:_:)
#elseif os(Linux) || os(FreeBSD)
private let sysStat: @convention(c) (UnsafePointer<CChar>, UnsafeMutablePointer<stat>) -> CInt = stat(_:_:)
#endif
```

**Comment by kylebrowning** [comment]
Im going to close this for now as this hasn't been something Ive been able to focus on.
