### ISSUE TITLE
Support for cert authentication

### ISSUE THREAD

**Issue by rafiki270** [kylebrowning/APNSwift#40]
It would be amazing to have access to cert authentication. In big corporation like ours we never get access to anything else :(

**Comment by weissi** [comment]
that shouldn't be hard to add because APNSwift uses swift-nio-ssl. So if it lets you configure the `TLSConfiguration` you can enable that.

**Comment by weissi** [comment]
actually, `APNSwiftConfiguration` exposes the `TLSConfiguration` already and you can change it too. @rafiki270 what exactly would you need?

**Comment by mosed** [comment]
It’s not clear for me either.  Would you be able to give an example how to configure this given a PEM file containing public and private key?  Thank you

**Comment by kylebrowning** [comment]
I think you could try this,
```
var apnsConfig = APNSwiftConfiguration(keyIdentifier: "9UC9ZLQ8YW",
                                       teamIdentifier: "ABBM6U9RM5",
                                       signer: signer,
                                       topic: "com.grasscove.Fern",
                                       environment: .sandbox)

apnsConfig.tlsConfiguration.privateKey = .file("key.pem")
```

Now, this probably won't work entirely because of the  header and the signer, so let me do a little work to make this work.

**Comment by kylebrowning** [comment]
Try this commit. https://github.com/kylebrowning/APNSwift/pull/45

**Comment by kylebrowning** [comment]
Eh, doesn't seem to work. Im not sure how to get TLSConfiguration to accept my pem correctly.

I get `missingProviderToken`

**Comment by mosed** [comment]
yes because for this type of connection I think also we dont use the `keyIdentifier` either.   And we should have to set the pem cert as well as the pem private key.   I just cant figure out how to get it to work

**Comment by kylebrowning** [comment]
IN that PR, `keyIdentifier` isn't used at all, even though its being configured. This was just a quick dirty way of testing it.

**Comment by kylebrowning** [comment]
@mosed https://github.com/swift-server/async-http-client/issues/27#issuecomment-489760481

I’ll look at this more in the evening

**Comment by kylebrowning** [comment]
@mosed @rafiki270 I got it working, will post example shortly after I get the new release out.

**Comment by kylebrowning** [comment]
#47

**Comment by kylebrowning** [comment]
You can see the APNSwiftPemExample to see how you may accomplish this.

**Comment by kylebrowning** [comment]
https://github.com/kylebrowning/APNSwift/blob/686c69561040054550e7bd9afe88f395ebb53c27/Sources/APNSwiftPemExample/main.swift#L33
