### ISSUE TITLE
the update from 1.2.0 to 1.2.1 is SemVer minor but was tagged as SemVer patch

### ISSUE THREAD

**Issue by weissi** [kylebrowning/APNSwift#52]
The diff between 1.2.0 and 1.2.1 contains

```
diff --git a/Sources/APNSwift/APNSwiftConnection.swift b/Sources/APNSwift/APNSwiftConnection.swift
index fc5ca49..5e2f9ea 100644
--- a/Sources/APNSwift/APNSwiftConnection.swift
+++ b/Sources/APNSwift/APNSwiftConnection.swift
@@ -154,6 +154,15 @@ public final class APNSwiftConnection {
      ```
      */
     public func send<Notification: APNSwiftNotification>(_ notification: Notification, pushType: APNSwiftConnection.PushType, to deviceToken: String, with encoder: JSONEncoder = JSONEncoder(), expiration: Date? = nil, priority: Int? = nil, collapseIdentifier: String? = nil, topic: String? = nil) -> EventLoopFuture<Void> {
+        let data: Data = try! encoder.encode(notification)        
+        var buffer = ByteBufferAllocator().buffer(capacity: data.count)
+        buffer.writeBytes(data)
+        return send(rawBytes: buffer, pushType: pushType, to: deviceToken)
+    }
+    
+    /// This is to be used with caution. APNSwift cannot gurantee delivery if you do not have the correct payload.
+    /// For more information see: [Creating APN Payload](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html)
+    public func send(rawBytes payload: ByteBuffer, pushType: APNSwiftConnection.PushType, to deviceToken: String, expiration: Date? = nil, priority: Int? = nil, collapseIdentifier: String? = nil, topic: String? = nil) -> EventLoopFuture<Void> {
             let streamPromise = channel.eventLoop.makePromise(of: Channel.self)
             multiplexer.createStreamChannel(promise: streamPromise) { channel, streamID in
                 let handlers: [ChannelHandler] = [
@@ -166,12 +175,8 @@ public final class APNSwiftConnection {
             }
             
             let responsePromise = channel.eventLoop.makePromise(of: Void.self)
-            let data: Data = try! encoder.encode(notification)
-            
-            var buffer = ByteBufferAllocator().buffer(capacity: data.count)
-            buffer.writeBytes(data)
             let context = APNSwiftRequestContext(
-                request: buffer,
+                request: payload,
                 responsePromise: responsePromise
             )
             
```

which adds a `public func`. Any additions to the API are SemVer _minor_, not _patch_. The correct version for 1.2.1 would've been 1.3.0.

The recommended way in SemVer to fix this is to push a new commit which reverts back to what 1.2.0 was and then to release that as 1.2.2. Following that a new version 1.3.0 should be released that is equivalent to what 1.2.1 is now.

Given that the chance of breakage is quite small here, I think we might also leave 1.2.1 as is (despite it violating SemVer) and releasing a 1.3.0 which is equivalent to 1.2.1 so that at least the latest available version is correctly versioned.

**Comment by kylebrowning** [comment]
Bah. Okay. Wil do.

**Comment by kylebrowning** [comment]
https://github.com/kylebrowning/APNSwift/releases/tag/1.3.0
