### ISSUE TITLE
important CI environments missing

### ISSUE THREAD

**Issue by weissi** [kylebrowning/APNSwift#53]
From what I can tell, right now we're CI'ing on 5.0 on 18.04 (ie. OpenSSL 1.1) only. Given that APNSwift essentially has code that works different for OpenSSL 1.0/OpenSSL 1.1; as well as for Swift 5.0/5.1, we need at least four environments :(

- [x] Swift 5.0 on 18.04 (ie. OpenSSL 1.1)
- [x] Swift 5.0 on 16.04 (ie. OpenSSL 1.0)
- [x] Swift 5.1 on 18.04 (ie. OpenSSL 1.1)
- [x] Swift 5.1 on 16.04 (ie. OpenSSL 1.0)

On top of that, we should make use of TSan (thread sanitizer) on 5.1 (`swift test --sanitize=thread`) as well as ASan (address sanitizer) (`swift test --sanitize=address`).

**Comment by kylebrowning** [comment]
Done.
