### ISSUE TITLE
[Open Call] READ ME! Do you use APNSwift? Want to help?

### ISSUE THREAD

**Issue by kylebrowning** [kylebrowning/APNSwift#55]
Two of the graduation paths for the [SSWG Incubation process ](https://github.com/swift-server/sswg/blob/master/process/incubation.md#graduation-criteria)out of sandbox are 

- Document that it is being used successfully in production by at least three independent end users which, in the SSWG judgement, are of adequate quality and scope.
- Have a healthy number of committers.

Eventually I would love to apply to a higher status but I will need the communities help. Just to clarify, I have no plans to abandon, or pawn off the project, just looking for others to help so we can graduate!

1. Are you using this in production? Attach a 🚀  below
2. Interested in co-maintainer Attach a 👍  below

(Note, ive added the two reactions below manually for ease of use.)

### Minimal Tasks
- [x] Publicly accessible source managed by an SCM such as github.com or similar 
- [x] Ecosystem
- [x] Concurrency / IO
- [x] Testing, CI and Release
- [x] Concurrency / IO
- [x] Conventions and Style
- [x] Longevity
- [x] Licensing

### Incubation Tasks
- [x] Document that it is being used successfully in production by at least three independent end users which, in the SSWG judgement, are of adequate quality and scope.
- [x] Have a healthy number of committers.
- [x] Demonstrate a substantial ongoing flow of commits and merged contributions.
- [ ] Receive a supermajority vote from the SSWG to move to Incubation stage.

### Graduation
- [x] Support new GA versions of Swift within 30d
- [x] CI setup for two latest Swift.org recommnded versions of Swift
- [x]  CI setup for two latest versions of Swift.org recommnded Linux distributions
- [x]  Unit tests for both macOS and Linux
- [x]  Use official docker (when appropriate)
- [ ]  Documented release methodology
- [x] All packages should always work with at least the latest released version of Swift
- [ ]  Explicitly define a project governance and committer process, ideally laid out in a GOVERNANCE.md file and OWNERS.md files respectively
- [ ]  Include list of adopters for at least the primary repo ideally laid out in an ADOPTERS.md files or logos on the project website
- [ ]  Optionally, have a [Developer Certificate of Origin](https://developercertificate.org) or a [Contributor License Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement)

**Comment by kylebrowning** [comment]
For those using it in production, can you give us a very rough sense of number of users, or number of requests per day? Also if you can, What are you using it for?

**Comment by itcohorts** [comment]
About 100-150 requests / day. Sorry, but I have an NDA on what I'm using it
for.

Benjamin Ingmire
m: 646.387.1399
e:  ben@itcohorts.com

**Comment by itcohorts** [comment]
🚀

Benjamin Ingmire
m: 646.387.1399
e:  ben@itcohorts.com

**Comment by kylebrowning** [comment]
thanks @itcohorts No worries on the NDA, totally get it. I realize this will be the case for a lot of developers, and Im wondering if it'll be possible to get enough information for the SSWG.

**Comment by itcohorts** [comment]
About 100-150 requests per day.

**Comment by aasatt** [comment]
I'm been able to send 120 pushes instantly, on a single connection. Would try more but I don't want to overload the limited devices I have.

**Comment by kylebrowning** [comment]
I noticed there are 7 people interested in maintaining. Any chance y'all could comment on this thread, or reach out to me privately?

**Comment by mipstian** [comment]
Hi! I'm using APNSwift to send about 40k pushes a day for Wipr (https://giorgiocalderolla.com/wipr.html)

**Comment by kylebrowning** [comment]
@lgaches @ksmandersen @tbartelmess @fabianfett are y'all still interested in helping me co-maintain?

**Comment by fabianfett** [comment]
@kylebrowning as pointed out on discord. I‘m down.

**Comment by tbartelmess** [comment]
@kylebrowning yes I am still interested (sorry for the late response)

**Comment by awasthi027** [comment]
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "ashi-api",
    products: [
        .library(name: "ashi-api", targets: ["App"]),
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
        
        // 🔵 Swift ORM (queries, models, relations, etc) built on SQLite 3.
        .package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0"),
        
        // 👤 Authentication and Authorization framework for Fluent.
        .package(url: "https://github.com/vapor/auth.git", from: "2.0.4"),
        
        // 🔏 JSON Web Token signing and verification (HMAC, RSA).
        .package(url: "https://github.com/vapor/jwt.git", from: "3.0.0"),
        
        // ✆ Enable phone number verification service.
        .package(url: "https://github.com/swift-aws/aws-sdk-swift.git", from: "3.3.0"),
        
        // ✆ Email Service
        .package(url: "https://github.com/twof/VaporMailgunService.git", from: "1.1.0"),
        
        .package(url: "https://github.com/vapor/leaf.git", from: "3.0.0-rc"),
        
         /* Notification third party service */
         .package(url: "https://github.com/kylebrowning/APNSwift.git", from: "1.7.0"),

    ],
    targets: [
        .target(name: "App", dependencies: ["FluentPostgreSQL", "Vapor", "Authentication","JWT","SNS","Mailgun","Leaf","APNSwift"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
Adding APNSSwift dependency. But it's working. APNS not getting download

**Comment by kylebrowning** [comment]
@awasthi027 APNSwift does not work with vapor 3

**Comment by tierracero** [comment]
Hi im using // swift-tools-version:5.2

ive tried the docu and other configs  but it will not  import APNSwift . I get a non existing error
<img width="871" alt="Captura de Pantalla 2020-12-06 a la(s) 12 10 01 p  m" src="https://user-images.githubusercontent.com/23512041/101288402-f98b4c80-37bb-11eb-98db-3c6ee00d92df.png">
