### ISSUE TITLE
[BUG] Dependancy issue when adding to Vapor project

### ISSUE THREAD

**Issue by handya** [kylebrowning/APNSwift#56]
After adding `APNSwift` to any of my Vapor 3.0.0 or 3.3.1 projects, using Swift package manger and then updating, half way through updating the packages, Swift package manager will hang and go to 100% cpu.
I'm able to build and run APNSwift and Vapor project independently but when adding APNSwift to Vapor it hangs.

It also hangs when only adding `swift-nio-http2` to a Vapor project.
It did not hang when changing APNSwift dependencies versions to: 
```
    dependencies: [
        .package(url: "https://github.com/apple/swift-nio", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-nio-ssl", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-nio-http2", .upToNextMinor(from: "0.1.0"))
    ],
```

**To Reproduce**
1. Add APNSwift to a Vapor project
```
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0"),
        .package(url: "https://github.com/kylebrowning/APNSwift.git", .upToNextMinor(from: "1.3.0"))
    ],
```
2. Update dependancies.
3. After updating a few packages Swift package manager should hang and go to 100% CPU on one thread.

**Expected behavior**
Vapor project should update successfully project.

**Platform:**
 - OS: Mac OS 10.14.5 (Xcode 10& 11 installed) & Mac OS 10.15 (Xcode 11)
 - APNSwift 1.3.0
 - Vapor 3.0.0

**Additional context**
Hopefully this is just me being dumb and not doing something correctly 🤞

**Comment by kylebrowning** [comment]
Hi @handya. This package will probably only work with Vapor 4. The hang is happening because of the swift tools package versions cc @tanner0101

I can't remember why exactly, and what would be needed to be done, but I don't believe NIO 2 works with Vapor 3.

**Comment by weissi** [comment]
Vapor 3 is unfortunately based on NIO 1. You'll only be able to use APNSwift together with Vapor 4.

**Comment by handya** [comment]
Ok, great, thanks for the info. I'll take a look at Vapor 4.

**Comment by kylebrowning** [comment]
Theres probably some commits before I went to NIO 2, can't find them currently, and I wouldn't recommend them, cause it's code from April that never went into production.

**Comment by kylebrowning** [comment]
Going to mark this as closed. Thanks.
