### ISSUE TITLE
[BUG] Build failed after add APNSwift through Swift Package Manager

### ISSUE THREAD

**Issue by idris11** [kylebrowning/APNSwift#58]
After add APNSwift, I try to cmd+B but I got fail. The error messages these below.
```
Undefined symbol: _ECDSA_SIG_free
Undefined symbol: _ECDSA_do_sign
Undefined symbol: _BIO_free
Undefined symbol: _BIO_s_mem
Undefined symbol: _PEM_read_bio_ECPrivateKey
Undefined symbol: _BN_num_bits
Undefined symbol: _EC_KEY_free
Undefined symbol: _BN_bn2bin
Undefined symbol: _BIO_new
Undefined symbol: _BIO_write
Undefined symbol: _SHA256_Final
Undefined symbol: _SHA256_Update
Undefined symbol: _SHA256_Init
```

**Comment by kylebrowning** [comment]
@idris11 It sounds like you do not have openssl installed. Or Xcode cannot find your openSSL headers.

Can you let me know what OS you're on and openssl version?

**Comment by idris11** [comment]
@kylebrowning thanks for your response. I am using OS Catalina. How to add openssl to xcode?, sorry to basic question.

**Comment by kylebrowning** [comment]
Not a problem! Do you have homebrew?

If you type `brew install openssl@1.1 `

That should do it for you. Then clean build in Xcode and run again!

**Comment by idris11** [comment]
@kylebrowning I installed OpenSSL, but the result is still error. Any advice? or how to include OpenSSL to our project?

**Comment by kylebrowning** [comment]
Did you follow the instructions from brew install?

more specifically
```

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

**Comment by idris11** [comment]
<img width="575" alt="Screen Shot 2019-11-15 at 14 57 52" src="https://user-images.githubusercontent.com/9367244/68926524-4fa7df00-07b8-11ea-92dd-d39e4beace19.png">

I already run your instruction, but still nothing work

**Comment by kylebrowning** [comment]
Is pkg config installed?

**Comment by idris11** [comment]
wooaahhhh.... thank you so much @kylebrowning, finally it's works.

**Comment by damiandizeo** [comment]
> wooaahhhh.... thank you so much @kylebrowning, finally it's works.
Hi, how did you make it work ? I still having the issue

**Comment by kylebrowning** [comment]
`brew install png-config`
`brew install openssl@1.1`

Then follow the instructions for exporting PKG-CONFIG

**Comment by damiandizeo** [comment]
> `brew install pkg-config`
> `brew install openssl@1.1`
> 
> Then follow the instructions for exporting PKG-CONFIG

Yeah, did all this but I get the following:

ld: warning: ignoring file /usr/local/Cellar/openssl@1.1/1.1.1d/lib/libssl.dylib, building for iOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/openssl@1.1/1.1.1d/lib/libcrypto.dylib, building for iOS-arm64 but attempting to link with file built for macOS-x86_64

and the list of Undefined symbols mentioned above.

As you see, I have all installed. I'm under macOS Catalina, Xcode 11.3 on a project on SwiftUI

![Captura de Pantalla 2020-02-05 a la(s) 12 56 01](https://user-images.githubusercontent.com/10283906/73858272-e4016b00-4816-11ea-8990-5ca700734a47.png)

**Comment by kylebrowning** [comment]
Delete your derived data and restart Xcode

**Comment by damiandizeo** [comment]
> Delete your derived data and restart Xcode

Thanks but no, it's doesn't work, too bad because I really need it . Do you have any other idea of what could be happening?

**Comment by kylebrowning** [comment]
Read the error message. 

```
building for iOS-arm64 but attempting to link with file built for macOS-x86_64
```

**Comment by kylebrowning** [comment]
Sounds like your Xcode target is iOS? This is not made for iOS.
