### ISSUE TITLE
Add overloads

### ISSUE THREAD

**Issue by grosch** [kylebrowning/APNSwift#66]
Seems like quite a bit of boilerplate to generate the configuration.  Would be easier if the initializer, instead of taking a signer parameter, had one method where you passed the path to the p8 file, and a second convenience initializer that instead took the path to the PEM and key files.

**Comment by kylebrowning** [comment]
@grosch The main reason that isn't the case currently is because it stops people from using alternatives to loading their keys securely. 

Another is that initializing those paths to p8 or pem is Blocking, and some people may do it on a main thread, so we wanted to separate them.

Can you give me an example of what you're saying would be easier? In my head you need teamIdentifier and keyIdentifier and signer, etc. passing these values all the time would be more cumbersome. I think I'm not fully understanding what you'd like to accomplish.

**Comment by grosch** [comment]
All of your examples are blocking, aren't they?  You're calling `.wait()` on everything.  Look at your PEM example from the README.  There's nothing 'custom' being done there.  It's confusing what you're doing with the signer because you're passing a zero length count to the signer buffer.  Then you're doing a bunch of stuff with the tls config.  It seems like all of that could be done by simply passing those two filenames into the constructor instead.

**Comment by grosch** [comment]
```swift
var apnsConfig = try APNSwiftConfiguration(keyIdentifier: "9UC9ZLQ8YW",
                                       teamIdentifier: "ABBM6U9RM5",
                                       topic: "com.grasscove.Fern",
                                       pemKey: "/path/to/key.pkey",
                                       pemFile: "/path/to/file.pem",
                                       environment: .sandbox)
```

**Comment by kylebrowning** [comment]
Examples are allowed to block. Just as they are allowed to force unwrap. They are simply that. Examples. 

Forcing users to block by passing in values to files will not work for everyone in production. 

I’d be happy to remove .wait in the example, but I’m not willing to make APNSConfiguration blocking by default. 

Pems out the gate are the old way of signing notifications and at any point could no longer be allowed by Apple. It’s not a first class citizen by APNSwift, and I’m not sure it will be. 

There is a lot to do with tls to get it work with PEM, on top of that using them plus files loaded into memory are major security issues.

**Comment by kylebrowning** [comment]
Also the examples don’t show custom signers. Anyone doing a custom AWSKeyStore signer would potentially understand they need to read what protocol to conform to. The example for custom signers does not exist because I cannot possibly show an example for every signer storage. Though you’re right. I should some custom form of a signer. 

These examples show the paths to least resistance in sending a push notification. While adding .wait is, not production worthy, and using a file key store is a editorial risk it’s just to get an execution of a task to your device ASAP.

**Comment by grosch** [comment]
I switched all my stuff to use the p8 a while ago...and then I discovered that PassKit still requires a PEM, and doesn't do the p8 :(

**Comment by grosch** [comment]
If you could show the examples non-blocking that would be awesome.   I'm also curious about the MultiThreadedEventLoopGroup piece.  If I'm sending a push due to a Vapor route being called, can I use the event loop that it provides already, or do I still create the MultiThreadedEventLoopGroup?

**Comment by kylebrowning** [comment]
@grosch You can use the following as an example in vapor

```swift
// configure.swift
    let signer = try! APNSwiftSigner(filePath: "/Users/kylebrowning/Desktop/AuthKey_9UC9ZLQ8YW.p8")
    let config = APNSwiftConfiguration(keyIdentifier: "9UC9ZLQ8YW", teamIdentifier: "ABBM6U9RM5", signer: signer, topic: "com.grasscove.Fern", environment: .sandbox)
    s.register(APNSwiftConnection.self) { c in
        return APNSwiftConnection.connect(configuration: config, on: c.eventLoop)
    }
    s.register(APNSwiftConfiguration.self) { c in
        return config
    }
```
// routes.swift
```swift
        let connection = try! c.make(APNSwiftConnection.self)
        let alert = APNSwiftPayload.APNSwiftAlert(title: "Hey There", subtitle: "Full moon sighting", body: "There was a full moon last night did you see it")
        let aps = APNSwiftPayload(alert: alert, badge: 1, sound: .normal("cow.wav"))
        let notification = AcmeNotification(acme2: ["tempValueExample"], aps: aps)
        connection.send(notification, pushType: .alert, to: "98AAD4A2398DDC58595F02FA307DF9A15C18B6111D1B806949549085A8E6A55D").whenSuccess {
            return "It sent!"
        }
```


I hand wrote this, so not 100% sure if it works in Vapor 4, but let me know.

**Comment by kylebrowning** [comment]
After speaking to a few people, Ive changed my mind on adding the convenience init. Once that is merged, you should be good to use less boiler plate. :P

**Comment by grosch** [comment]
In the register for the connection, there's not a `c.eventLoop`.

The other item I'm noticing might be an issue is that I can't change the topic.  When doing PassKit, the 'topic' is just the pass type, so it'll change frequently.

**Comment by kylebrowning** [comment]
@grosch Can you post me your configure.swift and routes.swift?

also, for the topic, you can set it on a per notification/send basis.

```
    public func send<Notification: APNSwiftNotification>(_ notification: Notification, pushType: APNSwiftConnection.PushType, to deviceToken: String, with encoder: JSONEncoder = JSONEncoder(), expiration: Date? = nil, priority: Int? = nil, collapseIdentifier: String? = nil, topic: String? = nil) -> EventLoopFuture<Void> {
```

**Comment by grosch** [comment]
The route becomes pretty simple now:

```swift
    func push(req: Request) throws -> EventLoopFuture<Void> {
        // Body for a PassKit notification should be an empty dictionary
        let data = "{}".data(using: .utf8)!
        var buffer = ByteBufferAllocator().buffer(capacity: data.count)
        buffer.writeBytes(data)

        return req.make(APNSwiftConnection.self)
            .send(rawBytes: buffer, pushType: .background, to: "device token goes here", topic: "pass.com.gargoylesoft.bella")
    }
```

Configure currently looks like this:

```swift
func configure(_ app: Application) throws {
    // Register providers first
    app.provider(FluentProvider())

    let configuration = PostgresConfiguration(hostname: "...", username: "...", password: "...", database: "...")
    app.databases.postgres(configuration: configuration, on: app.make())

    app.register(Migrations.self) { _ in Migrations() }

    let noSignerForPem = try APNSwiftSigner(buffer: ByteBufferAllocator().buffer(capacity: 1024))
    var apnsConfig = APNSwiftConfiguration(keyIdentifier: "",
                                       teamIdentifier: "...",
                                       signer: noSignerForPem,
                                       topic: "pass.com.gargoylesoft.bella",
                                       environment: .production)

    let key = try NIOSSLPrivateKey(file: "/Users/scott/bella/sign/passkey.pem", format: .pem)
    apnsConfig.tlsConfiguration.privateKey = NIOSSLPrivateKeySource.privateKey(key)
    apnsConfig.tlsConfiguration.certificateVerification = .noHostnameVerification
    apnsConfig.tlsConfiguration.certificateChain = try! [.certificate(.init(file: "/Users/scott/bella/sign/passcertificate.pem", format: .pem))]

    /*
    app.register(APNSwiftConnection.self) { c in
        APNSwiftConnection.connect(configuration: apnsConfig, on: c.lo)
    }
    */

    app.register(APNSwiftConfiguration.self) { _ in apnsConfig }

    try routes(app)
}
```

**Comment by kylebrowning** [comment]
That looks right to me, but c.eventLoop maybe has changed. 

it looks like you're doing `_ in apnsConfig`, if you add `c in ....` you'd get access to the context .

This seems to be a bit off topic for this current issue. Can you join the vapor discord and ping me in #beta (since vapor 4 is in beta)

**Comment by grosch** [comment]
What's your tag in there?

**Comment by kylebrowning** [comment]
@ocyrus#1337

**Comment by grosch** [comment]
Please remember to update the README.md when you have a chance :)

**Comment by kylebrowning** [comment]
@grosch for the `.wait`? you can just use `.whenComplete` or `.whenSuccess`

**Comment by grosch** [comment]
Sorry, no.  You added the PEM convenience initializer I see, so wanted to remind you to update that part of the README where you show doing a PEM instead of a p8.

**Comment by kylebrowning** [comment]
@grosch got it. done.
