### ISSUE TITLE
[BUG] expiration, priority, collapseIdentifier and topic parameters ignored in send(...) method

### ISSUE THREAD

**Issue by florianreinhart** [kylebrowning/APNSwift#69]
**Ignored Parameters in `send(...)`**
In `APNSwiftConnection.send(_ notification: Notification, ...)` the parameters `expiration`, `priority`, `collapseIdentifier` and `topic` are ignored and not passed to `send(rawBytes payload: ByteBuffer, ...)`.

**To Reproduce**
See [Line 169 in APNSwiftConnection.swift](https://github.com/kylebrowning/APNSwift/blob/88cc62bbf29bc767da44fb6777c678830ba318d2/Sources/APNSwift/APNSwiftConnection.swift#L169)

**Expected behavior**
All function parameters should be passed to `send(rawBytes payload: ByteBuffer, ...)`.

**Additional context**
The function documentation is also not up to date and mentions `bearerToken`.

**Comment by kylebrowning** [comment]
@florianreinhart https://github.com/kylebrowning/APNSwift/releases/tag/1.50
