### ISSUE TITLE
Support multiple configurations

### ISSUE THREAD

**Issue by grosch** [kylebrowning/APNSwift#83]
Please provide a way that a single server app can support both the normal app's push notification (i.e. via the p8) and also passkit notifications (i.e. via the PEM files). 

Right now we can't swap between them as needed.

**Comment by kylebrowning** [comment]
Why cant you open two APNSwifConnections with different configurations, and swap between them yourself?

**Comment by grosch** [comment]
Because there will be different threads running, and that configuration isn't thread safe.  Wouldn't it be possible for one thread to set it and be about to send a push, and then another thread sets it to the other one to do a push, and now the first one tries to push and fails.

**Comment by kylebrowning** [comment]
You have two configurations though. so wouldn't you just have two connections too?

**Comment by grosch** [comment]
When a request comes in I'd set app.apns.configuration to the one I want, and then I'd call req.apns.send. to all of the tokens I care about in a loop.  But then something running on the other thread would break.  Am I confused?

**Comment by grosch** [comment]
Created this request in vapor/apns instead
