### ISSUE TITLE
Supprt FCM

### ISSUE THREAD

**Issue by th-mustache-dk** [kylebrowning/APNSwift#84]
**Is your feature request related to a problem? Please describe.**
When sending push message you often need to support both iOS and Android devices, it would be very helpfull if one library supported both platforms

**Describe the solution you'd like**
Sending push messages to Android devices

**Describe alternatives you've considered**
Using Firebase push

**Comment by kylebrowning** [comment]
As discussed in the [pitch](https://forums.swift.org/t/feedback-nioapns-nio-based-apple-push-notification-service/24393)  this will not be done. 

The goal of this project is to support Apple only. 

The good news is I’m working on an equivalent for FCM.

**Comment by th-mustache-dk** [comment]
Any news on the FCM package?
