### ISSUE TITLE
APNSwift and Vapor 3

### ISSUE THREAD

**Issue by kschins** [kylebrowning/APNSwift#87]
Is there a release or branch that still supports Vapor 3? I am not ready to migrate to Vapor 4 yet but would still like to implement push notifications using APNSwift. I attempted to use the following code below in my `Package.swift` file:

`package(url: "https://github.com/kylebrowning/APNSwift.git", .exact("1.3.0"))`

Unfortunately this throws multiple errors (along with v1.7) about requiring certain versions of Vapor and other dependent packages.

**Comment by kylebrowning** [comment]
@kschins oof. there's probably an alpha of vapor/apns.

Can you try using this commit, https://github.com/vapor/apns/commit/5a9c3b8084788d3a34da5a72e9c1a4435468b963

**Comment by kylebrowning** [comment]
Actually that won't work.

**Comment by kylebrowning** [comment]
I think you'll have to make your own provider, but not sure which version of APNSwift you will have to use.

**Comment by kschins** [comment]
I appreciate the quick reply. I can try using a third party service like Pusher or Amazon SNS for now until I migrate to Vapor 4.

**Comment by kylebrowning** [comment]
AS much as Id hate to throw other packages out there, you could try this one, https://github.com/MihaelIsaev/FCM

**Comment by kschins** [comment]
Thank you, I will take a look!
