### ISSUE TITLE
Connection Deadlock caused by missing response & no timeout

### ISSUE THREAD

**Issue by xiao99xiao** [kylebrowning/APNSwift#93]
**Background**
I'm building a push service on Ubuntu 18.04 with Vapor 4 & Vapor/apns, using tls authentication.
The service is nothing but sending a push to my device after several hours and then another push,  running on Apple's sandbox push environment.

**The Bug**
After sometime, I found the push service will eventually fall into connection deadlock error reported as `[ ERROR ] Connection request timed out. This might indicate a connection deadlock in your application.`

After some investigation, I found it's the previous push which was sent some time ago, not getting its response.

As comparison, in the log, a normal push request should be like this
```
[ codes.vapor.application ] [ TRACE ] Re-using available connection (AsyncKit/ConnectionPool/EventLoopConnectionPool.swift:191)
[ codes.vapor.application ] [ DEBUG ] Send - starting up (APNSwift/APNSwiftConnection.swift:174)
[ codes.vapor.application ] [ INFO ] Send - sending (APNSwift/APNSwiftConnection.swift:204)
[ codes.vapor.application ] [ DEBUG ] Request - building (APNSwift/APNSwiftRequestEncoder.swift:68)
[ codes.vapor.application ] [ TRACE ] Request - built (APNSwift/APNSwiftRequestEncoder.swift:97)
[ codes.vapor.application ] [ TRACE ] Request - sent (APNSwift/APNSwiftRequestEncoder.swift:101)
[ codes.vapor.application ] [ DEBUG ] Response - received (APNSwift/APNSwiftStreamHandler.swift:36)
[ codes.vapor.application ] [ INFO ] Response - successful (APNSwift/APNSwiftStreamHandler.swift:53)
[ codes.vapor.application ] [ TRACE ] Releasing connection (AsyncKit/ConnectionPool/EventLoopConnectionPool.swift:262)
```

When the issue happens, response doesn't come, the log is like below
```
[ codes.vapor.application ] [ TRACE ] Re-using available connection (AsyncKit/ConnectionPool/EventLoopConnectionPool.swift:191)
[ codes.vapor.application ] [ DEBUG ] Send - starting up (APNSwift/APNSwiftConnection.swift:174)
[ codes.vapor.application ] [ INFO ] Send - sending (APNSwift/APNSwiftConnection.swift:204)
[ codes.vapor.application ] [ DEBUG ] Request - building (APNSwift/APNSwiftRequestEncoder.swift:68)
[ codes.vapor.application ] [ TRACE ] Request - built (APNSwift/APNSwiftRequestEncoder.swift:97)
[ codes.vapor.application ] [ TRACE ] Request - sent (APNSwift/APNSwiftRequestEncoder.swift:101)
```

As vapor/apns use only 1 max connection in configuration to initialize APNSwift, and the connection itself looks active, the connection pool will be completely jammed by the request above, waiting for its response.

So could anyone please enlighten me is there any way I could set a timeout for such case, or did I miss something?

**Platform:**
 - Ubuntu 18.04
 - Vapor 4.31.0
 - APNS 1.0.0
 - APNSwift 2.1.0

**Comment by Dong-Lin** [comment]
I have the same issue as well. It is no stable after the server running for 30 mins.

**Comment by kylebrowning** [comment]
It looks like this is happening with other services too https://github.com/jchambers/pushy/issues/816

**Comment by xiao99xiao** [comment]
@kylebrowning Yes, but the problem is, what if Apple doesn't fix it.
And adding at least a timeout would make the whole thing much solid.

**Comment by Dong-Lin** [comment]
@xiao99xiao Timeout maybe not the case. I tried the expiration parameter, still facing connection deadlock.
`       
 let payload = APNSwiftPayload(alert: .init(title: orderAPNSMessage),
                                      sound: .normal("default"))
        
        let expiry = Date().addingTimeInterval(5)
        
        return req.apns.send(payload, to: token, expiration: expiry)`

**Comment by xiao99xiao** [comment]
@Dong-Lin `Parameter expiration: a date that the notificaiton expires.` It's not a timeout.

**Comment by kylebrowning** [comment]
Thats correct, expiration is a value you used to Apple so that it can remove it from the users device, or attempt to push if the device comes on later.

**Comment by kylebrowning** [comment]
Okay if you're using `vapor/apns` that has a deadlock fix https://github.com/vapor/async-kit/commit/7457413e57dbfac762b32dd30c1caf2c55a02a3d

So I still need to dig to understand what's happening here.

**Comment by xiao99xiao** [comment]
@kylebrowning  Thanks. Didn't notice there is already a timeout parameter in Async Kit and is defaulting to 10 seconds,  even though it's not working 😂
BTW I really appreciate the timeout parameter could be configurable in vapor/apns, 10 seconds is way too long, sometimes.

**Comment by Dong-Lin** [comment]
@xiao99xiao looks like is possible to create a custom timeout. However, it would be a favor to ask from the author of APNS.  Official APNS wrap APNSwift with async-kit.   Here is my attempt to reduce the timeout from 10s to 5s.

https://github.com/Dong-Lin/apns/tree/feature/custom-connection-timeout

**Comment by kylebrowning** [comment]
It's a good thing I have commit access over there :)

**Comment by kylebrowning** [comment]
Please open a PR ill review.

**Comment by xiao99xiao** [comment]
@Dong-Lin Thanks for your PR https://github.com/vapor/apns/pull/24 . Looks pretty neat for me.

**Comment by Dong-Lin** [comment]
The timeout is not helping.  @kylebrowning we still suffer every day.

**Comment by jchambers** [comment]
> It looks like this is happening with other services too jchambers/pushy#816

@kylebrowning Indeed. I'll keep you posted as we learn more on our end. If you'd like to get in touch directly, I'm first-name-dot-last-name at gmail.

**Comment by kylebrowning** [comment]
Hey everyone @xiao99xiao @Dong-Lin. 

@jchambers just informed me that Apple has resolved this on their side. 

Please let us know if you continue to see anything.

**Comment by kylebrowning** [comment]
This seems to be resolved! But if not, please re-open.
